# Generated by Django 4.1.7 on 2023-05-06 13:11

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('web', '0002_remove_serviceprovider_location'),
    ]

    operations = [
        migrations.AddField(
            model_name='location',
            name='provider',
            field=models.OneToOneField(default=1, on_delete=django.db.models.deletion.CASCADE, to='web.serviceprovider'),
            preserve_default=False,
        ),
    ]
