# Generated by Django 4.1.7 on 2023-05-06 13:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('web', '0004_alter_providersettings_provider'),
    ]

    operations = [
        migrations.AddField(
            model_name='providersettings',
            name='logo_url',
            field=models.URLField(blank=True, null=True),
        ),
    ]
