# Generated by Django 4.1.7 on 2023-05-06 19:30

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('web', '0006_alter_providersettings_logo_url'),
    ]

    operations = [
        migrations.AlterField(
            model_name='location',
            name='provider',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='location', to='web.serviceprovider'),
        ),
    ]
