# Generated by Django 4.1.7 on 2023-05-06 19:38

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('web', '0008_location_districh'),
    ]

    operations = [
        migrations.RenameField(
            model_name='location',
            old_name='districh',
            new_name='district',
        ),
    ]
