# Generated by Django 4.1.7 on 2023-05-07 12:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('web', '0011_alter_payment_reservation'),
    ]

    operations = [
        migrations.AlterField(
            model_name='payment',
            name='information',
            field=models.TextField(blank=True, null=True),
        ),
    ]
