# Generated by Django 4.1.7 on 2023-05-07 16:48

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('web', '0012_alter_payment_information'),
    ]

    operations = [
        migrations.AlterField(
            model_name='availableservice',
            name='provider',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='available_services', to='web.serviceprovider'),
        ),
        migrations.AlterField(
            model_name='reservation',
            name='service',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='reservations', to='web.availableservice'),
        ),
        migrations.AlterField(
            model_name='subscriptions',
            name='provider',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='subscriptions', to='web.serviceprovider'),
        ),
    ]
