# Generated by Django 4.1.7 on 2023-05-13 08:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('web', '0014_serviceprovider_phone_alter_subscriptions_customer'),
    ]

    operations = [
        migrations.AddField(
            model_name='serviceprovider',
            name='service_capacity',
            field=models.IntegerField(default=1),
        ),
    ]
