# Generated by Django 4.1.7 on 2023-05-13 08:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('web', '0015_serviceprovider_service_capacity'),
    ]

    operations = [
        migrations.CreateModel(
            name='TempDeactivation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('provider', models.DateField()),
                ('hours', models.CharField(max_length=100)),
                ('excuse', models.CharField(max_length=100)),
            ],
        ),
    ]
