# Generated by Django 4.1.7 on 2023-05-13 08:25

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('web', '0016_tempdeactivation'),
    ]

    operations = [
        migrations.AddField(
            model_name='tempdeactivation',
            name='deactive_date',
            field=models.DateField(default='2023-05-05'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='tempdeactivation',
            name='excuse',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='tempdeactivation',
            name='hours',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='tempdeactivation',
            name='provider',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='temp_deactivations', to='web.serviceprovider'),
        ),
    ]
